### ISSUE TITLE
I cant receive message on channel?

### ISSUE THREAD

**Issue by htrxuan** [AgoraIO/Signaling#14]
Hi,

I try this function to receive message on channel

 channel.onMessageChannelReceive = function (account, uid, msg) { //code here });

before all works fine, but now cant.

Same for Agora RTM Web API:
channel.on('ChannelMessage', function (message, memberId) {
               // Your code.
             });

Totally, I cant trigger receive message on channel. Any problems with your server?

Please help me this issue

**Comment by plutoless** [comment]
i just did a quick test on our demo and it's working fine.
https://webdemo.agora.io/agora-web-showcase/examples/Agora-RTM-Tutorial-Web/
